name: Build

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
